apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: journeyman-backend-hpa
  namespace: roster-recall
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: journeyman-backend
  minReplicas: 5
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70