apiVersion: v1
kind: Service
metadata:
  name: journeyman-backend-service
  namespace: roster-recall
spec:
  selector:
    app: journeyman-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP
