apiVersion: apps/v1
kind: Deployment
metadata:
  name: journeyman-backend
  namespace: roster-recall
  labels:
    app: journeyman-backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: journeyman-backend
  template:
    metadata:
      labels:
        app: journeyman-backend
    spec:
      containers:
      - name: journeyman-backend
        image: journeyman-backend:latest  # Replace with your actual image
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_URL
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: ADMIN_TOKEN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
